version: '3'

services:
  acc-api:
    build: ./ACCollector-Server
    ports:
    - 8000:80
    networks:
    - accollector-network
    depends_on:
    - sql-server

  sql-server:
    image: microsoft/mssql-server-windows-express
    ports:
    - 1434:1433
    networks:
    - accollector-network
    environment:
    - sa_password=P@ssword1
    - ACCEPT_EULA=Y

networks:
  accollector-network: